package com.sampleproductapp.detaildesk.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xff0d6681)
val onPrimaryLight = Color(0xffffffff)
val secondaryLight = Color(0xff4c616b)
val onSecondaryLight = Color(0xffffffff)
val tertiaryLight = Color(0xff5c5b7e)
val onTertiaryLight = Color(0xffffffff)
val errorLight = Color(0xffba1a1a)
val onErrorLight = Color(0xffffffff)
val primaryContainerLight = Color(0xffbbeaff)
val onPrimaryContainerLight = Color(0xff001f29)
val secondaryContainerLight = Color(0xffcfe6f1)
val onSecondaryContainerLight = Color(0xff071e26)
val tertiaryContainerLight = Color(0xffe2dfff)
val onTertiaryContainerLight = Color(0xff181837)
val errorContainerLight = Color(0xffffdad6)
val onErrorContainerLight = Color(0xff410002)
val surfaceDimLight = Color(0xffd6dbde)
val surfaceLight = Color(0xfff5fafd)
val surfaceBrightLight = Color(0xfff5fafd)
val inverseSurfaceLight = Color(0xff2c3134)
val inverseOnSurfaceLight = Color(0xffedf1f5)
val inversePrimaryLight = Color(0xff89d0ee)
val onSurfaceLight = Color(0xff171c1f)
val onSurfaceVariantLight = Color(0xff40484c)
val outlineLight = Color(0xff70787d)
val outlineVarientLight = Color(0xffc0c8cc)
val scrimLight = Color(0x00000000)
